/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workforce/me/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get effective entitlements */
        get: operations["getMyWorkforceEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List capability catalog */
        get: operations["listWorkforceCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workforce roles */
        get: operations["listWorkforceRoles"];
        put?: never;
        /** Create workforce role */
        post: operations["createWorkforceRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        /** Get workforce role */
        get: operations["getWorkforceRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update workforce role metadata */
        patch: operations["updateWorkforceRole"];
        trace?: never;
    };
    "/api/v1/workforce/authorization/roles/{roleId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace non-privileged role capabilities
         * @description Privileged capability changes must use the approval workflow.
         */
        put: operations["replaceWorkforceRoleCapabilities"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workforce assignments */
        get: operations["listWorkforceAssignments"];
        put?: never;
        /**
         * Assign non-privileged role
         * @description Privileged role assignments must use the approval workflow.
         */
        post: operations["createWorkforceAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/assignments/{assignmentId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke workforce assignment */
        post: operations["revokeWorkforceAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List authorization change requests */
        get: operations["listAuthorizationChangeRequests"];
        put?: never;
        /** Request privileged authorization change */
        post: operations["createAuthorizationChangeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/change-requests/{requestId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve authorization change */
        post: operations["approveAuthorizationChangeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/authorization/change-requests/{requestId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject authorization change */
        post: operations["rejectAuthorizationChangeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/directory/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workforce subjects */
        get: operations["listWorkforceDirectorySubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/directory/organization-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizational units */
        get: operations["listWorkforceOrganizationUnits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workforce/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent workforce audit events */
        get: operations["listWorkforceAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CapabilityDefinition: {
            key: string;
            resource: string;
            action: string;
            /** @enum {unknown} */
            riskTier: "standard" | "sensitive" | "privileged";
            displayName: string;
            deprecated: boolean;
            catalogVersion: number;
        };
        AuthorizationScope: {
            /** @enum {unknown} */
            type: "global" | "market" | "showroom" | "department";
            ref: string;
        };
        WorkforceEntitlements: {
            /** Format: uuid */
            identitySubjectId: string;
            revision: string;
            capabilities: {
                key: string;
                /** @enum {unknown} */
                riskTier: "standard" | "sensitive" | "privileged";
                scopes: components["schemas"]["AuthorizationScope"][];
            }[];
        };
        WorkforceRole: {
            /** Format: uuid */
            id: string;
            key: string;
            displayName: string;
            description?: string | null;
            /** @enum {unknown} */
            status: "active" | "disabled";
            system: boolean;
            version: number;
            capabilityKeys: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateWorkforceRole: {
            key: string;
            displayName: string;
            description?: string;
        };
        UpdateWorkforceRole: {
            expectedVersion: number;
            displayName?: string;
            description?: string | null;
        };
        ReplaceRoleCapabilities: {
            expectedVersion: number;
            capabilityKeys: string[];
        };
        WorkforceAssignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            identitySubjectId: string;
            /** Format: uuid */
            roleId: string;
            roleKey: string;
            /** @enum {unknown} */
            status: "active" | "revoked";
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            reason: string;
            version: number;
            scopes: components["schemas"]["AuthorizationScope"][];
        };
        CreateWorkforceAssignment: {
            /** Format: uuid */
            identitySubjectId: string;
            /** Format: uuid */
            roleId: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt?: string;
            reason: string;
            scopes: components["schemas"]["AuthorizationScope"][];
        };
        VersionedMutation: {
            expectedVersion: number;
        };
        AuthorizationChangeRequest: {
            /** Format: uuid */
            id: string;
            requestType: string;
            /** @enum {unknown} */
            status: "pending" | "approved" | "rejected";
            /** @enum {unknown} */
            riskTier: "standard" | "sensitive" | "privileged";
            requesterRef: string;
            targetType: string;
            targetRef: string;
            reason: string;
            payload: unknown;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        CreateAuthorizationChangeRequest: {
            /** @enum {unknown} */
            requestType: "replace-role-capabilities" | "disable-role" | "create-privileged-assignment";
            /** @constant */
            riskTier: "privileged";
            /** @enum {unknown} */
            targetType: "workforce-role" | "workforce-subject";
            /** Format: uuid */
            targetRef: string;
            reason: string;
            payload: Record<string, never>;
        };
        AuthorizationDecision: {
            evidenceRef: string;
            reason?: string;
        };
        WorkforceDirectorySubject: {
            /** Format: uuid */
            id: string;
            externalSubject: string;
            status: string;
        };
        WorkforceOrganizationUnit: {
            /** Format: uuid */
            id: string;
            externalRef: string;
            /** @enum {unknown} */
            type: "market" | "showroom" | "department";
            displayName: string;
            status: string;
            source: string;
            revision: string;
            /** Format: date-time */
            observedAt: string;
        };
        WorkforceAuditEvent: {
            /** Format: uuid */
            id: string;
            actorRef?: string | null;
            action: string;
            resourceType: string;
            resourceId?: string | null;
            outcome: string;
            /** Format: uuid */
            correlationId: string;
            /** Format: date-time */
            occurredAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code?: string;
            /** Format: uuid */
            correlationId?: string;
        };
    };
    responses: {
        /** @description RFC Problem Details response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        RoleId: string;
        AssignmentId: string;
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyWorkforceEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective capabilities, scopes and authorization revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceEntitlements"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code-owned capability definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityDefinition"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System and custom roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRole"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkforceRole: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkforceRole"];
            };
        };
        responses: {
            /** @description Role created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRole"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getWorkforceRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role and current capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRole"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateWorkforceRole: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkforceRole"];
            };
        };
        responses: {
            /** @description Updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRole"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    replaceWorkforceRoleCapabilities: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRoleCapabilities"];
            };
        };
        responses: {
            /** @description Updated role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceRole"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workforce role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceAssignment"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createWorkforceAssignment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkforceAssignment"];
            };
        };
        responses: {
            /** @description Assignment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceAssignment"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeWorkforceAssignment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                assignmentId: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionedMutation"];
            };
        };
        responses: {
            /** @description Revoked assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceAssignment"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAuthorizationChangeRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorization approval queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationChangeRequest"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAuthorizationChangeRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuthorizationChangeRequest"];
            };
        };
        responses: {
            /** @description Change request created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationChangeRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    approveAuthorizationChangeRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizationDecision"];
            };
        };
        responses: {
            /** @description Approved request and applied change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationChangeRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    rejectAuthorizationChangeRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizationDecision"];
            };
        };
        responses: {
            /** @description Rejected request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationChangeRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceDirectorySubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Opaque workforce identity subjects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceDirectorySubject"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceOrganizationUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active and historical organization-unit projections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceOrganizationUnit"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listWorkforceAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent minimized audit-event views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkforceAuditEvent"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
