/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check liveness */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check readiness */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions */
        get: operations["listMySessions"];
        put?: never;
        post?: never;
        /**
         * Sign out all devices
         * @description Immediately deny every active local session owned by the verified
         *     customer and request subject-wide logout from CIAM.
         */
        delete: operations["revokeAllMySessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get identity security status
         * @description Returns email verification, MFA enrollment and current-session MFA
         *     evidence. Provider-backed fields are null when the protected CIAM
         *     administration bridge is unavailable.
         */
        get: operations["getMyIdentitySecurity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke session */
        delete: operations["revokeMySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List consents */
        get: operations["listMyConsents"];
        /** Update consents */
        put: operations["putMyConsent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/data-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data requests */
        get: operations["listMyDataRequests"];
        put?: never;
        /** Request data export/delete */
        post: operations["createMyDataRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/data-requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get data request */
        get: operations["getMyDataRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List garage */
        get: operations["listMyVehicles"];
        put?: never;
        /** Add a vehicle */
        post: operations["createMyVehicle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/vehicles/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Archive vehicle */
        delete: operations["deleteMyVehicle"];
        options?: never;
        head?: never;
        /** Update vehicle */
        patch: operations["updateMyVehicle"];
        trace?: never;
    };
    "/api/v1/vehicles/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicle models */
        get: operations["listVehicleModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/models/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vehicle model */
        get: operations["getVehicleModelBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/models/{slug}/commercial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current commercial data
         * @description Returns governed public price offers and promotions from one active commercial release. Inventory is intentionally excluded.
         */
        get: operations["getVehicleModelCommercialData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SourceMetadata: {
            sourceId: string;
            revision: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** @enum {unknown} */
            freshness: "fresh" | "stale" | "unavailable";
        };
        CustomerProfile: {
            displayName?: string | null;
            /** @enum {unknown} */
            locale: "vi" | "en";
            timezone: string;
            /** @enum {unknown} */
            market: "VN";
            communicationPreferences: components["schemas"]["CommunicationPreferences"];
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunicationPreferences: {
            email: boolean;
            sms: boolean;
            push: boolean;
        };
        CustomerProfilePatch: {
            displayName?: string | null;
            /** @enum {unknown} */
            locale?: "vi" | "en";
            timezone?: string;
            /** @enum {unknown} */
            market?: "VN";
            communicationPreferences?: {
                email?: boolean;
                sms?: boolean;
                push?: boolean;
            };
        };
        CustomerSession: {
            /** Format: uuid */
            id: string;
            isCurrent: boolean;
            /** @enum {unknown} */
            status: "active" | "expired" | "revoked";
            /** Format: date-time */
            authenticatedAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            revokedAt: string | null;
            deviceLabel: string | null;
            networkHint: string | null;
            userAgentSummary: string | null;
            mfaSatisfied: boolean;
            emailVerified: boolean | null;
        };
        RevokeSessionResult: {
            /** @enum {unknown} */
            reconciliation: "confirmed" | "manual_review_required" | "pending" | "retry_required";
            session: components["schemas"]["CustomerSession"];
        };
        RevokeAllSessionsResult: {
            locallyRevokedCount: number;
            /** @enum {unknown} */
            reconciliation: "confirmed" | "manual_review_required" | "retry_required";
        };
        CustomerIdentitySecurity: {
            currentSessionMfaSatisfied: boolean;
            emailVerified: boolean | null;
            mfaConfigured: boolean | null;
            /** @enum {unknown} */
            providerStatus: "available" | "unavailable";
        };
        ConsentRecord: {
            /** @enum {unknown} */
            purpose: "analytics" | "marketing_email" | "marketing_sms" | "marketing_push" | "personalization";
            policyVersion: string;
            /** @enum {unknown} */
            state: "granted" | "withdrawn";
            /** @enum {unknown} */
            source: "customer_portal" | "mobile" | "operations_admin" | "system_import";
            /** Format: date-time */
            occurredAt: string;
        };
        ConsentWrite: {
            /** @enum {unknown} */
            purpose: "analytics" | "marketing_email" | "marketing_sms" | "marketing_push" | "personalization";
            policyVersion: string;
            /** @enum {unknown} */
            state: "granted" | "withdrawn";
        };
        ConsentWriteBatch: {
            consents: components["schemas"]["ConsentWrite"][];
        };
        DataRequestInput: {
            /** @enum {unknown} */
            type: "export" | "delete";
        };
        DataRequest: {
            /** Format: uuid */
            id: string;
            /** @enum {unknown} */
            type: "export" | "delete";
            /** @enum {unknown} */
            status: "requested" | "processing" | "partially_completed" | "completed" | "rejected";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            completedAt: string | null;
        };
        CreateCustomerGarageEntry: {
            /** Format: uuid */
            claimedVehicleVariantId: string;
            nickname?: string | null;
            /** @default false */
            isPrimary: boolean;
        };
        UpdateCustomerGarageEntry: {
            nickname?: string | null;
            isPrimary?: boolean;
        };
        CustomerGarageEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            claimedVehicleVariantId: string;
            nickname: string | null;
            isPrimary: boolean;
            /** @enum {unknown} */
            source: "self-reported" | "imported";
            /** @enum {unknown} */
            status: "active" | "archived";
            /**
             * @description A garage entry is not proof of verified vehicle ownership.
             * @constant
             */
            ownershipStatus: "unverified";
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VehicleModelProjection: {
            /** Format: uuid */
            id: string;
            brandCode: string;
            modelCode: string;
            slug: string;
            name: string;
            category: string;
            /** @enum {unknown} */
            commercialStatus: "announced" | "active" | "discontinued";
            modelYear: number | null;
            /** @enum {unknown} */
            market: "VN";
            releaseVersion: string;
            variants: components["schemas"]["VehicleVariantProjection"][];
            source: components["schemas"]["SourceMetadata"];
        };
        VehicleVariantProjection: {
            /** Format: uuid */
            id: string;
            variantCode: string;
            name: string;
            /** @enum {unknown} */
            commercialStatus: "announced" | "active" | "discontinued";
            seats: number | null;
            drivetrain: string | null;
            grossBatteryCapacityKwh: number | null;
            usableBatteryCapacityKwh: number | null;
            declaredRangeKm: number | null;
            rangeTestStandard: string | null;
            maximumAcChargePowerKw: number | null;
            maximumDcChargePowerKw: number | null;
            connectorStandards: string[];
        };
        CommercialSourceMetadata: {
            sourceId: string;
            revision: string;
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            effectiveFrom: string;
            /** Format: date-time */
            expiresAt: string | null;
            /** @constant */
            freshness: "fresh";
        };
        PriceOffer: {
            /** Format: uuid */
            variantId: string;
            offerCode: string;
            /** @enum {unknown} */
            priceType: "msrp" | "list" | "option" | "service";
            /** @enum {unknown} */
            market: "VN";
            currency: string;
            amountMinor: string;
            /** @enum {unknown} */
            taxTreatment: "tax_inclusive" | "tax_exclusive" | "not_applicable";
            /** @enum {unknown} */
            channel: "public" | "retail" | "fleet" | "employee";
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            source: components["schemas"]["CommercialSourceMetadata"];
        };
        Promotion: {
            promotionCode: string;
            promotionVersion: string;
            title: string;
            /** @enum {unknown} */
            channel: "public" | "retail" | "fleet" | "employee";
            /** Format: uuid */
            vehicleModelId: string | null;
            /** Format: uuid */
            vehicleVariantId: string | null;
            /** @enum {unknown} */
            benefitType: "fixed_amount" | "percentage" | "in_kind" | "composite";
            benefitAmountMinor: string | null;
            benefitPercentage: number | null;
            currency: string | null;
            /** @enum {unknown} */
            stackingPolicy: "exclusive" | "stackable" | "rule_based";
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo: string | null;
            source: components["schemas"]["CommercialSourceMetadata"];
        };
        VehicleCommercialData: {
            /** @enum {unknown} */
            market: "VN";
            releaseVersion: string;
            priceOffers: components["schemas"]["PriceOffer"][];
            promotions: components["schemas"]["Promotion"][];
        };
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            correlationId: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description RFC 9457 Problem Details */
        Problem: {
            headers: {
                "X-Correlation-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        IfMatch: string;
        GarageIfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Entity revision validator */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process is serving requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required API dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                        dependencies: {
                            /** @constant */
                            database: "up";
                        };
                    };
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current customer profile */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerProfilePatch"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSession"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeAllMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local denial count and provider reconciliation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllSessionsResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMyIdentitySecurity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current customer identity assurance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerIdentitySecurity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeMySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revocation intent and reconciliation state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMyConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current consent state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecord"][];
                };
            };
        };
    };
    putMyConsent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentWriteBatch"];
            };
        };
        responses: {
            /** @description Current consent state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecord"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMyDataRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject-scoped data requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createMyDataRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataRequestInput"];
            };
        };
        responses: {
            /** @description Request accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMyDataRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subject-scoped data request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRequest"];
                };
            };
            /** @description Data request not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listMyVehicles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer garage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerGarageEntry"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createMyVehicle: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerGarageEntry"];
            };
        };
        responses: {
            /** @description Unverified customer garage entry */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerGarageEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteMyVehicle: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["GarageIfMatch"];
            };
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived garage entry */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerGarageEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMyVehicle: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["GarageIfMatch"];
            };
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerGarageEntry"];
            };
        };
        responses: {
            /** @description Updated garage entry */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerGarageEntry"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listVehicleModels: {
        parameters: {
            query?: {
                market?: "VN";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleModelProjection"][];
                };
            };
        };
    };
    getVehicleModelBySlug: {
        parameters: {
            query?: {
                market?: "VN";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleModelProjection"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getVehicleModelCommercialData: {
        parameters: {
            query?: {
                market?: "VN";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current verified commercial facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleCommercialData"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
